### ISSUE TITLE
bug: en/analyst/dataset/available page gives 500 error in production

### ISSUE THREAD

**Issue by joshgamache** [button-inc/emissions-elt-demo#233]
### 🐛 Description of the bug

The `[lng]/analyst/dataset/available` page gives `500 - Internal Server Error.` and does not load. This same page loads in a local development environment. 

### To reproduce
1. While logged in, navigate to [the Available Datasets page](http://localhost:3000/en/analyst/dataset/available)

**Actual outcome**: The page displays `500 - Internal Server Error.`.

Console log: 
```console
-> GET http://34.125.36.177.nip.io/en/analyst/dataset/available 500 (Internal Server Error)
```

**Expected outcome**: The page displays a table with available datasets.

**Comment by joshgamache** [comment]
Here are some error logs in **local** development. They don't prevent the page from loading, but they _do_ display in the console. 

```console
Warning: Failed prop type: The prop `children` is marked as required in `Box`, but its value is `undefined`.
    at eval (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/Box/Box.js:131:5)
    at Header (webpack-internal:///(sc_client)/./app/components/layout/Header.tsx:28:66)
    at SessionProvider (webpack-internal:///(sc_client)/./node_modules/next-auth/react/index.js:453:24)
    at StyleRegistry (webpack-internal:///(sc_client)/./node_modules/next/node_modules/styled-jsx/dist/index/index.js:537:34)
    at StyledJsxRegistry (webpack-internal:///(sc_client)/./lib/utilities/registry.tsx:22:3)
    at DefaultLayout (webpack-internal:///(sc_client)/./app/components/layout/DefaultLayout.tsx:22:3)
    at Lazy
    at body
    at html
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:77:5)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:32:3)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:127:3)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:73:5)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:34:5)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at InsertedHTML (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:1114:33)
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, direction: ..., testID: ..., space: ...};
  <Spacer {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {direction: ..., testID: ..., space: ...};
  <Spacer key={someKey} {...props} />
    at eval (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/StackView/StackView.js:80:5)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/react-native-web/dist/cjs/exports/View/index.js:29:25)
    at eval (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/Box/Box.js:131:5)
    at PortalProviderComponent (webpack-internal:///(sc_client)/./node_modules/@gorhom/portal/lib/commonjs/components/portalProvider/PortalProvider.js:23:3)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/ThemeProvider/ThemeProvider.js:43:5)
    at ViewportProvider (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/ViewportProvider/ViewportProvider.js:31:5)
    at A11yInfoProvider (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/A11yInfoProvider/index.js:29:5)
    at HydrationProvider (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/BaseProvider/HydrationContext.js:54:5)
    at BaseProvider (webpack-internal:///(sc_client)/./node_modules/@telus-uds/components-base/lib/BaseProvider/index.js:30:5)
    at Header (webpack-internal:///(sc_client)/./app/components/layout/Header.tsx:28:66)
    at SessionProvider (webpack-internal:///(sc_client)/./node_modules/next-auth/react/index.js:453:24)
    at StyleRegistry (webpack-internal:///(sc_client)/./node_modules/next/node_modules/styled-jsx/dist/index/index.js:537:34)
    at StyledJsxRegistry (webpack-internal:///(sc_client)/./lib/utilities/registry.tsx:22:3)
    at DefaultLayout (webpack-internal:///(sc_client)/./app/components/layout/DefaultLayout.tsx:22:3)
    at Lazy
    at body
    at html
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:77:5)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:32:3)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:127:3)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:73:5)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:34:5)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at InsertedHTML (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:1114:33)
accessibilityOrientation is deprecated. Use aria-orientation.
accessibilityRole is deprecated. Use role.
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Page (webpack-internal:///(sc_client)/./app/components/route/Home.tsx:31:3)
    at Lazy
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:450:5)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at Suspense
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:73:5)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at div
    at SessionProvider (webpack-internal:///(sc_client)/./node_modules/next-auth/react/index.js:453:24)
    at StyleRegistry (webpack-internal:///(sc_client)/./node_modules/next/node_modules/styled-jsx/dist/index/index.js:537:34)
    at StyledJsxRegistry (webpack-internal:///(sc_client)/./lib/utilities/registry.tsx:22:3)
    at DefaultLayout (webpack-internal:///(sc_client)/./app/components/layout/DefaultLayout.tsx:22:3)
    at Lazy
    at body
    at html
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:185:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:220:3)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:409:5)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:418:3)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:459:3)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:357:3)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:16:32)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:33:3)
    at Lazy
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:77:5)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:32:3)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:127:3)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:73:5)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:91:3)    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:34:5)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at ServerComponentWrapper (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:389:28)
    at InsertedHTML (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/app-render.js:1114:33)
accessibilityLevel is deprecated. Use aria-level.
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
```

**Comment by joshgamache** [comment]
_Research_
Using a local build and serve with `yarn run build` + `yarn run start`, the 505 error also occurs. The log to the server console from this is 
```
Error: Page changed from static to dynamic at runtime /en/analyst/dataset/available, see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at doRender (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/base-server.js:728:23)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/base-server.js:831:28)
    at async /home/josh/forge/emissions-elt-demo/app/node_modules/next/dist/server/response-cache/index.js:83:36
```

**Comment by joshgamache** [comment]
To resolve the above error, `export const dynamic = "force-dynamic"` causes the page to partially render. Further errors are exposed in the console:
```
GET http://34.125.36.177.nip.io/en/analyst/dataset/available net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
3299-df7e2d4d90fdb706.js:1 
 
 GET http://34.125.36.177.nip.io/api/auth/session net::ERR_CONNECTION_TIMED_OUT
3299-df7e2d4d90fdb706.js:1 
 [next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Failed to fetch 
{error: {…}, url: '/api/auth/session', message: 'Failed to fetch'}
3299-df7e2d4d90fdb706.js:1 
 
 POST http://34.125.36.177.nip.io/api/auth/_log net::ERR_CONNECTION_TIMED_OUT
```

The pages will render, but the data tables stay in a loading state indefinitely. Sometimes the `/api/auth/session` connection succeeds, but the data tables still do not load (with no console errors observed).

**Comment by joshgamache** [comment]
Turns out, there were more errors with the values not in place for `.env` in production and them not passing along to Docker before build properly. PR incoming.
